version: '3'
services:
  db:
    image: mysql:5.7.24
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '8080:8080'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql