version: '3'
services:
  db:
    image: mysql:5.7.24
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql
  api:
    build: .
    ports:
     - "8000:8000"
    depends_on:
      - db

volumes:
  bundle:
    driver: local
