version: '3.6'

services: 
  python:
    image: python:latest
    ports:
     - '80:80'
    volumes:
      - type: bind
        source: .
        target: /scripts
    command: tail -f /dev/null
    links:
      - 'mysql'

  mysql:
    image: mysql/mysql-server:latest
    ports:
     - '3306:3306'
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mysql-db1
        target: /var/lib/mysql


volumes: 
  mysql-db1:
    external: true